___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports



In [1]:
import numpy as np

## Dataset

We will use the famous Iris Data set.
_____
More info on the data set:
https://en.wikipedia.org/wiki/Iris_flower_data_set

## Reading in the Data Set

We've already downloaded the dataset, its in this folder. So let's open it up. 

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [8]:
# X

In [9]:
y = iris.target

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)

In [14]:
y.shape

(150, 3)

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
scaler_object = MinMaxScaler()

In [20]:
scaler_object.fit(X_train)

MinMaxScaler()

In [21]:
scaled_X_train = scaler_object.transform(X_train)

In [22]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [23]:
X_train.max()

7.7

In [24]:
scaled_X_train.max()

1.0

## Building the Network with Keras

Let's build a simple neural network!

In [27]:
from keras.models import Sequential
from keras.layers import Dense

In [28]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


## Fit (Train) the Model

In [32]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
4/4 - 0s - loss: 0.1658 - accuracy: 0.9700 - 8ms/epoch - 2ms/step
Epoch 2/150
4/4 - 0s - loss: 0.1650 - accuracy: 0.9700 - 6ms/epoch - 1ms/step
Epoch 3/150
4/4 - 0s - loss: 0.1645 - accuracy: 0.9700 - 11ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 0.1647 - accuracy: 0.9800 - 7ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 0.1649 - accuracy: 0.9700 - 12ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 0.1645 - accuracy: 0.9700 - 13ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 0.1632 - accuracy: 0.9700 - 12ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 0.1613 - accuracy: 0.9800 - 9ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 0.1600 - accuracy: 0.9700 - 7ms/epoch - 2ms/step
Epoch 10/150
4/4 - 0s - loss: 0.1583 - accuracy: 0.9700 - 10ms/epoch - 2ms/step
Epoch 11/150
4/4 - 0s - loss: 0.1584 - accuracy: 0.9700 - 9ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 0.1584 - accuracy: 0.9700 - 6ms/epoch - 1ms/step
Epoch 13/150
4/4 - 0s - loss: 0.1569 - accuracy: 0.9700 

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [36]:
# Spits out probabilities by default.
model.predict(scaled_X_test)

2/2 [==============================] - 0s 2ms/step


array([[7.20355194e-04, 9.64969695e-01, 3.43100056e-02],
       [9.89779294e-01, 1.01939812e-02, 2.68205877e-05],
       [4.67295430e-12, 1.75558846e-04, 9.99824464e-01],
       [3.08309041e-04, 8.95670295e-01, 1.04021296e-01],
       [1.20380806e-04, 8.61629248e-01, 1.38250351e-01],
       [9.80084836e-01, 1.98501628e-02, 6.49221402e-05],
       [8.98364652e-03, 9.76746976e-01, 1.42693566e-02],
       [1.02228519e-07, 3.01333722e-02, 9.69866514e-01],
       [3.28417809e-05, 3.67596269e-01, 6.32370949e-01],
       [3.73786804e-03, 9.76619065e-01, 1.96430273e-02],
       [4.46851891e-06, 2.51997292e-01, 7.47998297e-01],
       [9.80881691e-01, 1.89895071e-02, 1.28807747e-04],
       [9.88284945e-01, 1.16721652e-02, 4.28312160e-05],
       [9.82587397e-01, 1.73058044e-02, 1.06848107e-04],
       [9.90080774e-01, 9.89091769e-03, 2.83620666e-05],
       [3.13204218e-04, 9.30121303e-01, 6.95654675e-02],
       [1.81714679e-08, 1.19588105e-02, 9.88041162e-01],
       [4.60971193e-03, 9.73339

In [39]:
np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 4ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [40]:
model.metrics_names

['loss', 'accuracy']

In [41]:
model.evaluate(x=scaled_X_test,y=y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.0974 - accuracy: 0.9600


[0.09738905727863312, 0.9599999785423279]

In [42]:
from sklearn.metrics import confusion_matrix,classification_report

In [43]:
predictions = np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 2ms/step


In [44]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [45]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [46]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [47]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [166]:
model.save('myfirstmodel.h5')

In [167]:
from keras.models import load_model

In [168]:
newmodel = load_model('myfirstmodel.h5')

In [169]:
newmodel.predict_classes(X_test)

array([2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1,
       1, 2, 2, 2, 2, 2], dtype=int64)

Great job! You now know how to preprocess data, train a neural network, and evaluate its classification performance!